
breakers:

  tier1:
    delay: 5
    durability: 16
    item: WOODEN_PICKAXE

  tier2:
    delay: 4
    durability: 64
    item: STONE_PICKAXE

  tier3:
    delay: 3
    durability: 256
    item: GOLD_PICKAXE

  tier4:
    delay: 2
    durability: 512
    item: IRON_PICKAXE

  tier5:
    delay: 1
    durability: 2048
    item: DIAMOND_PICKAXE